theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}Gb ({Mupi}%)"
icons = true
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "enp0s20u2"
speed_up = false
graph_up = false

[[block]]
block = "sound"

[[block]]
block = "pacman"

[[block]]
block = "temperature"
interval = 10
format = "{average}°C"
collapsed = false

[[block]]
block = "weather"
format = "{temp}°C"
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "battery"
device = "BAT1"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
